/*
  xmlSession.cpp
  filterable xml listing service for Session
  generated by w3sys RAD tools

*/
#include <iostream>
#include <iomanip>
#include "cgiClass.h"
#include "ocTypes.h"
#include "cgiTemplates.h"
#include "connectstring"
#include "Session.hpp"

using namespace std;

int main( int argc, char ** argv)
{
  cgiScript script( "text/xml" );
  Session_Obj Session;
  script << "<?xml version='1.0' encoding='UTF-8' standalone='yes'?>" << endl;
  script << "<Session id=\"" << Session.key() << "\">" << endl;
  script << "  <User_Id>" << endl;
  script << "    " << Session.User_Id << endl;
  script << "  </User_Id>" << endl;
  script << "  <UUID>" << endl;
  script << "    " << Session.UUID << endl;
  script << "  </UUID>" << endl;
  script << "  <Instance_Stamp>" << endl;
  script << "    " << Session.Instance_Stamp << endl;
  script << "  </Instance_Stamp>" << endl;
  script << "  <XML_Variables>" << endl;
  script << "    " << Session.XML_Variables << endl;
  script << "  </XML_Variables>" << endl;
  script << "</Session>" << endl;
}

#include "read_write_base.cpp"

