create table Form_Label
(
  Id bigint primary key auto_increment NOT NULL,
  form_name text,
  label_a text,
  label_b text,
  label_c text,
  label_d text,
  label_e text,
  label_f text,
  label_g text,
  label_h text,
  label_i text,
  label_j text,
  label_k text,
  label_l text,
  label_m text,
  label_n text,
  label_o text,
  label_p text,
  label_q text,
  label_r text,
  label_s text,
  label_t text,
  label_u text,
  label_v text,
  label_w text
);

create table Form_Data
(
  Id bigint primary key auto_increment NOT NULL,
  Form_Label_Id bigint,
  form_name text,
  sent datetime,
  recipient text,
  is_read int,
  read_on datetime,
  data_a text,
  data_b text,
  data_c text,
  data_d text,
  data_e text,
  data_f text,
  data_g text,
  data_h text,
  data_i text,
  data_j text,
  data_k text,
  data_l text,
  data_m text,
  data_n text,
  data_o text,
  data_p text,
  data_q text,
  data_r text,
  data_s text,
  data_t text,
  data_u text,
  data_v text,
  data_w text
);


